-- MySQL Script generated by MySQL Workbench
-- lun. 17 avril 2023 17:40:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `IdUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `Mdp` VARCHAR(70) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Pseudo` VARCHAR(45) NOT NULL,
  `Droit` INT NOT NULL,
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) VISIBLE,
  PRIMARY KEY (`IdUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recette` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recette` (
  `IdRecette` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `IdCréateur` INT NOT NULL,
  `Notemoy` DECIMAL NULL,
  `Nb_personne` INT NOT NULL,
  `Temps_prep` INT NOT NULL,
  `Temps_cuis` INT NULL,
  `Description` VARCHAR(180) NOT NULL,
  `Instruction` TEXT NOT NULL,
  `État` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdRecette`, `IdCréateur`),
  INDEX `Créateur_idx` (`IdCréateur` ASC) VISIBLE,
  CONSTRAINT `Créateur`
    FOREIGN KEY (`IdCréateur`)
    REFERENCES `mydb`.`Utilisateur` (`IdUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commentaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commentaire` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commentaire` (
  `IdCommentaire` INT NOT NULL AUTO_INCREMENT,
  `Commentaire` VARCHAR(180) NULL,
  `Note` INT NOT NULL,
  `IdAuteur` INT NOT NULL,
  `Recette_com` INT NOT NULL,
  `Date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdCommentaire`, `IdAuteur`, `Recette_com`),
  INDEX `Auteur_idx` (`IdAuteur` ASC) VISIBLE,
  INDEX `Recette_com_idx` (`Recette_com` ASC) VISIBLE,
  CONSTRAINT `Auteur`
    FOREIGN KEY (`IdAuteur`)
    REFERENCES `mydb`.`Utilisateur` (`IdUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Recette_comm`
    FOREIGN KEY (`Recette_com`)
    REFERENCES `mydb`.`Recette` (`IdRecette`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingrédient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingrédient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingrédient` (
  `IdIngrédient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Quantité` FLOAT NOT NULL,
  `Unité` VARCHAR(45) NULL,
  `Prix` FLOAT NOT NULL DEFAULT 0,
  `Recette` INT NOT NULL,
  PRIMARY KEY (`IdIngrédient`, `Recette`),
  INDEX `Recette_idx` (`Recette` ASC) VISIBLE,
  CONSTRAINT `IdRecette`
    FOREIGN KEY (`Recette`)
    REFERENCES `mydb`.`Recette` (`IdRecette`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `IdTag` INT NOT NULL AUTO_INCREMENT,
  `Mot_clé` VARCHAR(45) NOT NULL,
  `Recette_assoc` INT NULL,
  PRIMARY KEY (`IdTag`),
  INDEX `fk_Tag_1_idx` (`Recette_assoc` ASC) VISIBLE,
  CONSTRAINT `fk_Tag_1`
    FOREIGN KEY (`Recette_assoc`)
    REFERENCES `mydb`.`Recette` (`IdRecette`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recette_pref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recette_pref` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recette_pref` (
  `Id_recette` INT NOT NULL,
  `Id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`Id_recette`, `Id_utilisateur`),
  INDEX `fk_Rectte_pref_2_idx` (`Id_utilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Rectte_pref_1`
    FOREIGN KEY (`Id_recette`)
    REFERENCES `mydb`.`Recette` (`IdRecette`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rectte_pref_2`
    FOREIGN KEY (`Id_utilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`IdUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


